# Generated by Django 4.2.2 on 2023-12-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdesc', models.TextField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibility', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=250)),
                ('experience', models.ImageField(upload_to='')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
