# Generated by Django 4.2.2 on 2023-12-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
