# Generated by Django 4.2.2 on 2023-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='education',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='experience',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='max_salary',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='min_salary',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
    ]
